app = "kaigpt"
primary_region = "iad"

[http_service]
  internal_port = 11434
  force_https = true
  processes = ["app"]

[experimental]
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  memory = "1gb"
  memory_mb = 1024
  cpu_kind = "shared"
  cpus = 1
